In [194]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [195]:
df = pd.read_csv('/Users/sujal/OneDrive/Desktop/Review4/dataset/hormuz_trade_uncleaned.csv')
df

,date,vessel_name,mmsi,flag,trade_tier,transit_status,toll_usd,rerouted,commodity,destination,...,insurance_cost_usd,days_delayed,extra_fuel_tonnes,reroute_penalty_usd,total_transit_cost_usd,naval_escort_status,estimated_cargo_value_usd,total_asset_value_at_risk_usd,continent,inflation_premium_per_unit
0,2026-03-01,MarchVessel_1,100000001,India,Privileged,Passed,0,No,Various,Global Port,...,40000,0,0,0,40000,Light (Cooperative),80000000,160000000,Asia,NaN
1,2026-03-01,MarchVessel_2,100000002,Iran,Privileged,Passed,0,No,Crude Oil,Hidden,...,70000,0,0,0,70000,Internal (IRGC Navy),240000000,380000000,Asia,0.035000
2,2026-03-01,MarchVessel_3,100000003,Iran,Privileged,Passed,0,No,Crude Oil,Hidden,...,70000,0,0,0,70000,Internal (IRGC Navy),240000000,380000000,Asia,0.035000
3,2026-03-02,MarchVessel_4,100000004,Greece,Taxed,Passed,2000000,No,Various,Global Port,...,1000000,0,0,0,3000000,NaN,80000000,160000000,Europe,NaN
4,2026-03-02,MarchVessel_5,100000005,Iran,Privileged,Passed,0,No,Crude Oil,Hidden,...,70000,0,0,0,70000,Internal (IRGC Navy),240000000,380000000,Asia,0.035000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,2026-05-31,Iron Carrier 15,386403601,UK,Blocked,Rerouted,0,Yes (Cape of Good Hope),Bulk Carrier,Mumbai,...,67500,12,480,607200,674700,NaN,50000000,95000000,Europe,NaN
1886,2026-05-31,Global Star 34,369408512,Iran,Privileged,Passed,0,No,Container Ship,Hidden/Private,...,55000,0,0,0,55000,Internal (IRGC Navy),150000000,260000000,Asia,3.666667
1887,2026-05-31,Red Spirit 36,559556395,Liberia,Taxed,Passed,2000000,No,LNG Carrier,Houston,...,2750000,0,0,0,4750000,NaN,200000000,420000000,Africa,1.397059
1888,2026-05-31,Eastern Titan 10,238114122,Russia,Privileged,Passed,0,No,Container Ship,Hidden/Private,...,55000,0,0,0,55000,Heavy (PLAN/RF Navy),150000000,260000000,Eurasia,3.666667
1889,2026-05-31,Golden Trader 56,287324253,Marshall Islands,Taxed,Passed,2000000,No,Crude Oil Tanker,Singapore,...,1750000,0,0,0,3750000,NaN,240000000,380000000,Oceania,1.875000

In [196]:
df.isnull().sum()

date                                0
vessel_name                         0
mmsi                                0
flag                                0
trade_tier                          0
transit_status                      0
toll_usd                            0
rerouted                            0
commodity                           0
destination                         0
payment_rail                        0
ship_hull_value_usd                 0
insurance_premium_delta_pct         0
insurance_cost_usd                  0
days_delayed                        0
extra_fuel_tonnes                   0
reroute_penalty_usd                 0
total_transit_cost_usd              0
naval_escort_status              1211
estimated_cargo_value_usd           0
total_asset_value_at_risk_usd       0
continent                           0
inflation_premium_per_unit        499
dtype: int64

In [197]:
df = df.drop(['naval_escort_status'], axis = 1)

In [198]:
df.isnull().sum()

date                               0
vessel_name                        0
mmsi                               0
flag                               0
trade_tier                         0
transit_status                     0
toll_usd                           0
rerouted                           0
commodity                          0
destination                        0
payment_rail                       0
ship_hull_value_usd                0
insurance_premium_delta_pct        0
insurance_cost_usd                 0
days_delayed                       0
extra_fuel_tonnes                  0
reroute_penalty_usd                0
total_transit_cost_usd             0
estimated_cargo_value_usd          0
total_asset_value_at_risk_usd      0
continent                          0
inflation_premium_per_unit       499
dtype: int64

In [199]:
df.dtypes

date                                 str
vessel_name                          str
mmsi                               int64
flag                                 str
trade_tier                           str
transit_status                       str
toll_usd                           int64
rerouted                             str
commodity                            str
destination                          str
payment_rail                         str
ship_hull_value_usd                int64
insurance_premium_delta_pct      float64
insurance_cost_usd                 int64
days_delayed                       int64
extra_fuel_tonnes                  int64
reroute_penalty_usd                int64
total_transit_cost_usd             int64
estimated_cargo_value_usd          int64
total_asset_value_at_risk_usd      int64
continent                            str
inflation_premium_per_unit       float64
dtype: object

In [200]:
df['inflation_premium_per_unit'] = df['inflation_premium_per_unit'].fillna(
    df['inflation_premium_per_unit'].mode()[0]
)

In [201]:
df

,date,vessel_name,mmsi,flag,trade_tier,transit_status,toll_usd,rerouted,commodity,destination,...,insurance_premium_delta_pct,insurance_cost_usd,days_delayed,extra_fuel_tonnes,reroute_penalty_usd,total_transit_cost_usd,estimated_cargo_value_usd,total_asset_value_at_risk_usd,continent,inflation_premium_per_unit
0,2026-03-01,MarchVessel_1,100000001,India,Privileged,Passed,0,No,Various,Global Port,...,0.05,40000,0,0,0,40000,80000000,160000000,Asia,0.035000
1,2026-03-01,MarchVessel_2,100000002,Iran,Privileged,Passed,0,No,Crude Oil,Hidden,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
2,2026-03-01,MarchVessel_3,100000003,Iran,Privileged,Passed,0,No,Crude Oil,Hidden,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
3,2026-03-02,MarchVessel_4,100000004,Greece,Taxed,Passed,2000000,No,Various,Global Port,...,1.25,1000000,0,0,0,3000000,80000000,160000000,Europe,0.035000
4,2026-03-02,MarchVessel_5,100000005,Iran,Privileged,Passed,0,No,Crude Oil,Hidden,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,2026-05-31,Iron Carrier 15,386403601,UK,Blocked,Rerouted,0,Yes (Cape of Good Hope),Bulk Carrier,Mumbai,...,0.15,67500,12,480,607200,674700,50000000,95000000,Europe,0.035000
1886,2026-05-31,Global Star 34,369408512,Iran,Privileged,Passed,0,No,Container Ship,Hidden/Private,...,0.05,55000,0,0,0,55000,150000000,260000000,Asia,3.666667
1887,2026-05-31,Red Spirit 36,559556395,Liberia,Taxed,Passed,2000000,No,LNG Carrier,Houston,...,1.25,2750000,0,0,0,4750000,200000000,420000000,Africa,1.397059
1888,2026-05-31,Eastern Titan 10,238114122,Russia,Privileged,Passed,0,No,Container Ship,Hidden/Private,...,0.05,55000,0,0,0,55000,150000000,260000000,Eurasia,3.666667
1889,2026-05-31,Golden Trader 56,287324253,Marshall Islands,Taxed,Passed,2000000,No,Crude Oil Tanker,Singapore,...,1.25,1750000,0,0,0,3750000,240000000,380000000,Oceania,1.875000

In [202]:
df.isnull().sum()

date                             0
vessel_name                      0
mmsi                             0
flag                             0
trade_tier                       0
transit_status                   0
toll_usd                         0
rerouted                         0
commodity                        0
destination                      0
payment_rail                     0
ship_hull_value_usd              0
insurance_premium_delta_pct      0
insurance_cost_usd               0
days_delayed                     0
extra_fuel_tonnes                0
reroute_penalty_usd              0
total_transit_cost_usd           0
estimated_cargo_value_usd        0
total_asset_value_at_risk_usd    0
continent                        0
inflation_premium_per_unit       0
dtype: int64

In [203]:
df.dtypes

date                                 str
vessel_name                          str
mmsi                               int64
flag                                 str
trade_tier                           str
transit_status                       str
toll_usd                           int64
rerouted                             str
commodity                            str
destination                          str
payment_rail                         str
ship_hull_value_usd                int64
insurance_premium_delta_pct      float64
insurance_cost_usd                 int64
days_delayed                       int64
extra_fuel_tonnes                  int64
reroute_penalty_usd                int64
total_transit_cost_usd             int64
estimated_cargo_value_usd          int64
total_asset_value_at_risk_usd      int64
continent                            str
inflation_premium_per_unit       float64
dtype: object

In [204]:
# datatype change for date
df['date'] = pd.to_datetime(df['date'])
df.dtypes

date                             datetime64[us]
vessel_name                                 str
mmsi                                      int64
flag                                        str
trade_tier                                  str
transit_status                              str
toll_usd                                  int64
rerouted                                    str
commodity                                   str
destination                                 str
payment_rail                                str
ship_hull_value_usd                       int64
insurance_premium_delta_pct             float64
insurance_cost_usd                        int64
days_delayed                              int64
extra_fuel_tonnes                         int64
reroute_penalty_usd                       int64
total_transit_cost_usd                    int64
estimated_cargo_value_usd                 int64
total_asset_value_at_risk_usd             int64
continent                                   str
inflation_premium_per_unit              float64
dtype: object

In [205]:
df

,date,vessel_name,mmsi,flag,trade_tier,transit_status,toll_usd,rerouted,commodity,destination,...,insurance_premium_delta_pct,insurance_cost_usd,days_delayed,extra_fuel_tonnes,reroute_penalty_usd,total_transit_cost_usd,estimated_cargo_value_usd,total_asset_value_at_risk_usd,continent,inflation_premium_per_unit
0,2026-03-01,MarchVessel_1,100000001,India,Privileged,Passed,0,No,Various,Global Port,...,0.05,40000,0,0,0,40000,80000000,160000000,Asia,0.035000
1,2026-03-01,MarchVessel_2,100000002,Iran,Privileged,Passed,0,No,Crude Oil,Hidden,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
2,2026-03-01,MarchVessel_3,100000003,Iran,Privileged,Passed,0,No,Crude Oil,Hidden,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
3,2026-03-02,MarchVessel_4,100000004,Greece,Taxed,Passed,2000000,No,Various,Global Port,...,1.25,1000000,0,0,0,3000000,80000000,160000000,Europe,0.035000
4,2026-03-02,MarchVessel_5,100000005,Iran,Privileged,Passed,0,No,Crude Oil,Hidden,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,2026-05-31,Iron Carrier 15,386403601,UK,Blocked,Rerouted,0,Yes (Cape of Good Hope),Bulk Carrier,Mumbai,...,0.15,67500,12,480,607200,674700,50000000,95000000,Europe,0.035000
1886,2026-05-31,Global Star 34,369408512,Iran,Privileged,Passed,0,No,Container Ship,Hidden/Private,...,0.05,55000,0,0,0,55000,150000000,260000000,Asia,3.666667
1887,2026-05-31,Red Spirit 36,559556395,Liberia,Taxed,Passed,2000000,No,LNG Carrier,Houston,...,1.25,2750000,0,0,0,4750000,200000000,420000000,Africa,1.397059
1888,2026-05-31,Eastern Titan 10,238114122,Russia,Privileged,Passed,0,No,Container Ship,Hidden/Private,...,0.05,55000,0,0,0,55000,150000000,260000000,Eurasia,3.666667
1889,2026-05-31,Golden Trader 56,287324253,Marshall Islands,Taxed,Passed,2000000,No,Crude Oil Tanker,Singapore,...,1.25,1750000,0,0,0,3750000,240000000,380000000,Oceania,1.875000

In [206]:
df.insert(0, 'vessel_id', range(1, len(df) + 1))

In [207]:
df

,vessel_id,date,vessel_name,mmsi,flag,trade_tier,transit_status,toll_usd,rerouted,commodity,...,insurance_premium_delta_pct,insurance_cost_usd,days_delayed,extra_fuel_tonnes,reroute_penalty_usd,total_transit_cost_usd,estimated_cargo_value_usd,total_asset_value_at_risk_usd,continent,inflation_premium_per_unit
0,1,2026-03-01,MarchVessel_1,100000001,India,Privileged,Passed,0,No,Various,...,0.05,40000,0,0,0,40000,80000000,160000000,Asia,0.035000
1,2,2026-03-01,MarchVessel_2,100000002,Iran,Privileged,Passed,0,No,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
2,3,2026-03-01,MarchVessel_3,100000003,Iran,Privileged,Passed,0,No,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
3,4,2026-03-02,MarchVessel_4,100000004,Greece,Taxed,Passed,2000000,No,Various,...,1.25,1000000,0,0,0,3000000,80000000,160000000,Europe,0.035000
4,5,2026-03-02,MarchVessel_5,100000005,Iran,Privileged,Passed,0,No,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,1886,2026-05-31,Iron Carrier 15,386403601,UK,Blocked,Rerouted,0,Yes (Cape of Good Hope),Bulk Carrier,...,0.15,67500,12,480,607200,674700,50000000,95000000,Europe,0.035000
1886,1887,2026-05-31,Global Star 34,369408512,Iran,Privileged,Passed,0,No,Container Ship,...,0.05,55000,0,0,0,55000,150000000,260000000,Asia,3.666667
1887,1888,2026-05-31,Red Spirit 36,559556395,Liberia,Taxed,Passed,2000000,No,LNG Carrier,...,1.25,2750000,0,0,0,4750000,200000000,420000000,Africa,1.397059
1888,1889,2026-05-31,Eastern Titan 10,238114122,Russia,Privileged,Passed,0,No,Container Ship,...,0.05,55000,0,0,0,55000,150000000,260000000,Eurasia,3.666667
1889,1890,2026-05-31,Golden Trader 56,287324253,Marshall Islands,Taxed,Passed,2000000,No,Crude Oil Tanker,...,1.25,1750000,0,0,0,3750000,240000000,380000000,Oceania,1.875000

In [208]:
df['rerouted'] = df['rerouted'].map({
    'Yes (Cape of Good Hope)': 1,
    'No': 0
}).astype(int)

In [209]:
df

,vessel_id,date,vessel_name,mmsi,flag,trade_tier,transit_status,toll_usd,rerouted,commodity,...,insurance_premium_delta_pct,insurance_cost_usd,days_delayed,extra_fuel_tonnes,reroute_penalty_usd,total_transit_cost_usd,estimated_cargo_value_usd,total_asset_value_at_risk_usd,continent,inflation_premium_per_unit
0,1,2026-03-01,MarchVessel_1,100000001,India,Privileged,Passed,0,0,Various,...,0.05,40000,0,0,0,40000,80000000,160000000,Asia,0.035000
1,2,2026-03-01,MarchVessel_2,100000002,Iran,Privileged,Passed,0,0,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
2,3,2026-03-01,MarchVessel_3,100000003,Iran,Privileged,Passed,0,0,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
3,4,2026-03-02,MarchVessel_4,100000004,Greece,Taxed,Passed,2000000,0,Various,...,1.25,1000000,0,0,0,3000000,80000000,160000000,Europe,0.035000
4,5,2026-03-02,MarchVessel_5,100000005,Iran,Privileged,Passed,0,0,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,1886,2026-05-31,Iron Carrier 15,386403601,UK,Blocked,Rerouted,0,1,Bulk Carrier,...,0.15,67500,12,480,607200,674700,50000000,95000000,Europe,0.035000
1886,1887,2026-05-31,Global Star 34,369408512,Iran,Privileged,Passed,0,0,Container Ship,...,0.05,55000,0,0,0,55000,150000000,260000000,Asia,3.666667
1887,1888,2026-05-31,Red Spirit 36,559556395,Liberia,Taxed,Passed,2000000,0,LNG Carrier,...,1.25,2750000,0,0,0,4750000,200000000,420000000,Africa,1.397059
1888,1889,2026-05-31,Eastern Titan 10,238114122,Russia,Privileged,Passed,0,0,Container Ship,...,0.05,55000,0,0,0,55000,150000000,260000000,Eurasia,3.666667
1889,1890,2026-05-31,Golden Trader 56,287324253,Marshall Islands,Taxed,Passed,2000000,0,Crude Oil Tanker,...,1.25,1750000,0,0,0,3750000,240000000,380000000,Oceania,1.875000

In [210]:
df.dtypes

vessel_id                                 int64
date                             datetime64[us]
vessel_name                                 str
mmsi                                      int64
flag                                        str
trade_tier                                  str
transit_status                              str
toll_usd                                  int64
rerouted                                  int64
commodity                                   str
destination                                 str
payment_rail                                str
ship_hull_value_usd                       int64
insurance_premium_delta_pct             float64
insurance_cost_usd                        int64
days_delayed                              int64
extra_fuel_tonnes                         int64
reroute_penalty_usd                       int64
total_transit_cost_usd                    int64
estimated_cargo_value_usd                 int64
total_asset_value_at_risk_usd             int64
continent                                   str
inflation_premium_per_unit              float64
dtype: object

In [211]:
df

,vessel_id,date,vessel_name,mmsi,flag,trade_tier,transit_status,toll_usd,rerouted,commodity,...,insurance_premium_delta_pct,insurance_cost_usd,days_delayed,extra_fuel_tonnes,reroute_penalty_usd,total_transit_cost_usd,estimated_cargo_value_usd,total_asset_value_at_risk_usd,continent,inflation_premium_per_unit
0,1,2026-03-01,MarchVessel_1,100000001,India,Privileged,Passed,0,0,Various,...,0.05,40000,0,0,0,40000,80000000,160000000,Asia,0.035000
1,2,2026-03-01,MarchVessel_2,100000002,Iran,Privileged,Passed,0,0,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
2,3,2026-03-01,MarchVessel_3,100000003,Iran,Privileged,Passed,0,0,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
3,4,2026-03-02,MarchVessel_4,100000004,Greece,Taxed,Passed,2000000,0,Various,...,1.25,1000000,0,0,0,3000000,80000000,160000000,Europe,0.035000
4,5,2026-03-02,MarchVessel_5,100000005,Iran,Privileged,Passed,0,0,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,1886,2026-05-31,Iron Carrier 15,386403601,UK,Blocked,Rerouted,0,1,Bulk Carrier,...,0.15,67500,12,480,607200,674700,50000000,95000000,Europe,0.035000
1886,1887,2026-05-31,Global Star 34,369408512,Iran,Privileged,Passed,0,0,Container Ship,...,0.05,55000,0,0,0,55000,150000000,260000000,Asia,3.666667
1887,1888,2026-05-31,Red Spirit 36,559556395,Liberia,Taxed,Passed,2000000,0,LNG Carrier,...,1.25,2750000,0,0,0,4750000,200000000,420000000,Africa,1.397059
1888,1889,2026-05-31,Eastern Titan 10,238114122,Russia,Privileged,Passed,0,0,Container Ship,...,0.05,55000,0,0,0,55000,150000000,260000000,Eurasia,3.666667
1889,1890,2026-05-31,Golden Trader 56,287324253,Marshall Islands,Taxed,Passed,2000000,0,Crude Oil Tanker,...,1.25,1750000,0,0,0,3750000,240000000,380000000,Oceania,1.875000

In [212]:
df['rerouted'] = df['rerouted'].astype(bool)
df.dtypes

vessel_id                                 int64
date                             datetime64[us]
vessel_name                                 str
mmsi                                      int64
flag                                        str
trade_tier                                  str
transit_status                              str
toll_usd                                  int64
rerouted                                   bool
commodity                                   str
destination                                 str
payment_rail                                str
ship_hull_value_usd                       int64
insurance_premium_delta_pct             float64
insurance_cost_usd                        int64
days_delayed                              int64
extra_fuel_tonnes                         int64
reroute_penalty_usd                       int64
total_transit_cost_usd                    int64
estimated_cargo_value_usd                 int64
total_asset_value_at_risk_usd             int64
continent                                   str
inflation_premium_per_unit              float64
dtype: object

In [213]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
outlier_summary = {}
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    outlier_summary[col] = len(outliers)
print("Outlier count per column:\n")
print(outlier_summary)

Outlier count per column:

{'vessel_id': 0, 'mmsi': 0, 'toll_usd': 422, 'ship_hull_value_usd': 0, 'insurance_premium_delta_pct': 422, 'insurance_cost_usd': 290, 'days_delayed': 0, 'extra_fuel_tonnes': 0, 'reroute_penalty_usd': 0, 'total_transit_cost_usd': 0, 'estimated_cargo_value_usd': 0, 'total_asset_value_at_risk_usd': 0, 'inflation_premium_per_unit': 284}

In [214]:
df

,vessel_id,date,vessel_name,mmsi,flag,trade_tier,transit_status,toll_usd,rerouted,commodity,...,insurance_premium_delta_pct,insurance_cost_usd,days_delayed,extra_fuel_tonnes,reroute_penalty_usd,total_transit_cost_usd,estimated_cargo_value_usd,total_asset_value_at_risk_usd,continent,inflation_premium_per_unit
0,1,2026-03-01,MarchVessel_1,100000001,India,Privileged,Passed,0,False,Various,...,0.05,40000,0,0,0,40000,80000000,160000000,Asia,0.035000
1,2,2026-03-01,MarchVessel_2,100000002,Iran,Privileged,Passed,0,False,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
2,3,2026-03-01,MarchVessel_3,100000003,Iran,Privileged,Passed,0,False,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
3,4,2026-03-02,MarchVessel_4,100000004,Greece,Taxed,Passed,2000000,False,Various,...,1.25,1000000,0,0,0,3000000,80000000,160000000,Europe,0.035000
4,5,2026-03-02,MarchVessel_5,100000005,Iran,Privileged,Passed,0,False,Crude Oil,...,0.05,70000,0,0,0,70000,240000000,380000000,Asia,0.035000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,1886,2026-05-31,Iron Carrier 15,386403601,UK,Blocked,Rerouted,0,True,Bulk Carrier,...,0.15,67500,12,480,607200,674700,50000000,95000000,Europe,0.035000
1886,1887,2026-05-31,Global Star 34,369408512,Iran,Privileged,Passed,0,False,Container Ship,...,0.05,55000,0,0,0,55000,150000000,260000000,Asia,3.666667
1887,1888,2026-05-31,Red Spirit 36,559556395,Liberia,Taxed,Passed,2000000,False,LNG Carrier,...,1.25,2750000,0,0,0,4750000,200000000,420000000,Africa,1.397059
1888,1889,2026-05-31,Eastern Titan 10,238114122,Russia,Privileged,Passed,0,False,Container Ship,...,0.05,55000,0,0,0,55000,150000000,260000000,Eurasia,3.666667
1889,1890,2026-05-31,Golden Trader 56,287324253,Marshall Islands,Taxed,Passed,2000000,False,Crude Oil Tanker,...,1.25,1750000,0,0,0,3750000,240000000,380000000,Oceania,1.875000

In [215]:
df.isnull().sum()

vessel_id                        0
date                             0
vessel_name                      0
mmsi                             0
flag                             0
trade_tier                       0
transit_status                   0
toll_usd                         0
rerouted                         0
commodity                        0
destination                      0
payment_rail                     0
ship_hull_value_usd              0
insurance_premium_delta_pct      0
insurance_cost_usd               0
days_delayed                     0
extra_fuel_tonnes                0
reroute_penalty_usd              0
total_transit_cost_usd           0
estimated_cargo_value_usd        0
total_asset_value_at_risk_usd    0
continent                        0
inflation_premium_per_unit       0
dtype: int64

In [216]:
df.to_csv("Cleaned.csv", index=False)

Visualizations

Top Countries by Trade Volume

In [ ]:
top_countries = (
    df.groupby('flag')['total_transit_cost_usd']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

fig = px.bar(
    top_countries,
    x='flag',
    y='total_transit_cost_usd',
    title="Top Countries by Trade Volume",
    color='total_transit_cost_usd'
)

fig.show()

Region-wise Trade Distribution

In [218]:
region_dist = (
    df.groupby('continent')['total_transit_cost_usd']
    .sum()
    .reset_index()
)

fig = px.pie(
    region_dist,
    names='continent',
    values='total_transit_cost_usd',
    title="Region-wise Trade Distribution"
)

fig.show()

Monthly/Yearly Trade Trend

In [219]:
# Extract month
df['month'] = df['date'].dt.to_period('M').astype(str)

monthly_trend = (
    df.groupby('month')['total_transit_cost_usd']
    .sum()
    .reset_index()
)

fig = px.line(
    monthly_trend,
    x='month',
    y='total_transit_cost_usd',
    title="Monthly Trade Trend",
    markers=True
)

fig.show()

Relation between total_transist_cost and Commodity

In [224]:
px.box(df, x='commodity', y='total_transit_cost_usd')

Model Training using Random Forest Classifier

In [235]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

df = df.dropna()

target = 'transit_status'

relevant_features = [
    'mmsi',
    'flag',
    'trade_tier',
    'commodity',
    'destination',
    'payment_rail',
    'continent'
]

X = df[relevant_features]
y = df[target]

le = LabelEncoder()
y = le.fit_transform(y)

X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(n_estimators=100, random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9126984126984127
Classification Report:
               precision    recall  f1-score   support

           0       0.17      0.08      0.11        25
           1       1.00      1.00      1.00       214
           2       0.85      0.93      0.89       139

    accuracy                           0.91       378
   macro avg       0.67      0.67      0.66       378
weighted avg       0.89      0.91      0.90       378

Confusion Matrix:
 [[  2   0  23]
 [  0 214   0]
 [ 10   0 129]]

In [237]:
import joblib

joblib.dump(model, "rf_model.pkl")
joblib.dump(le, "label_encoder.pkl")
joblib.dump(X.columns, "columns.pkl")

['columns.pkl']

In [239]:

new_data = pd.DataFrame([{
    'mmsi': 123456789,
    'flag': 'Panama',
    'trade_tier': 'High',
    'commodity': 'Oil',
    'destination': 'China',
    'payment_rail': 'SWIFT',
    'continent': 'Asia'
}])

new_data = pd.get_dummies(new_data)
new_data = new_data.reindex(columns=X.columns, fill_value=0)

prediction = model.predict(new_data)
predicted_label = le.inverse_transform(prediction)

print("\nPredicted Transit Status:", predicted_label[0])

Predicted Transit Status: Rerouted

Predict Growth Using Linear Regression

In [242]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import joblib


df = df.sort_values(by=['flag'])

df['growth'] = df.groupby('flag')['total_transit_cost_usd'].pct_change()
df = df.dropna()

df = df.drop(columns=['vessel_id','vessel_name','mmsi'], errors='ignore')

y = df['growth']
X = df.drop(columns=['growth'])

X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, y_pred))
print("R2:", r2_score(y_test, y_pred))

joblib.dump({
    'model': model,
    'scaler': scaler,
    'columns': X.columns.tolist()
}, "country_growth_model.pkl")

loaded = joblib.load("country_growth_model.pkl")
model_loaded = loaded['model']
scaler_loaded = loaded['scaler']

sample = X.iloc[0:1]
sample_scaled = scaler_loaded.transform(sample)
prediction = model_loaded.predict(sample_scaled)

print("Predicted Growth:", prediction)

MSE: 1.761816796656524
R2: 0.09687364807672805
Predicted Growth: [-0.296]

In [232]:
import pandas as pd

country_summary = df.groupby("flag").agg(
    total_trade_volume_usd=("estimated_cargo_value_usd", "sum"),
    total_trades=("vessel_id", "count"),
    average_trade_value_usd=("estimated_cargo_value_usd", "mean"),
    commodities=("commodity", lambda x: ";".join(x.dropna().unique()))
).reset_index()
country_summary.insert(0, "summary_id", range(1, len(country_summary) + 1))

country_summary["date"] = pd.Timestamp.now()
country_summary = country_summary[
    [
        "summary_id",
        "flag",
        "total_trade_volume_usd",
        "total_trades",
        "average_trade_value_usd",
        "commodities",
        "date"
    ]
]
country_summary.to_csv("CountrySummary.csv", index=False)

print("CountrySummary.csv created successfully!")

CountrySummary.csv created successfully!